services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env.test #テスト用の.env
        - NODE_VER=23-alpine3.20
    tty: true
    volumes:
      - ./frontend:/home/node/app/frontend
      - node_modules_test:/home/node/app/node_modules
      - ./frontend/nginx.test.conf:/etc/nginx/conf.d/nginx.conf
      - ./certs_test:/etc/nginx/certs #テスト用証明書
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - php
    environment:
      - VITE_API_BASE_URL=http://php:9000

  php:
    build: ./php
    volumes:
      - ./php/src:/var/www/html
    expose:
      - "9000"
    environment:
      SPOTIFY_CLIENT_ID: dummy_test_client_id
      SPOTIFY_CLIENT_SECRET: dummy_test_secret
      TMDB_API_KEY: Bearer test_dummy_token

volumes:
  node_modules_test:
