services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env.local
        - NODE_VER=23-alpine3.20
    tty: true
    volumes:
      - ./frontend/nginx.local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - php
    environment:
      - VITE_API_BASE_URL=http://php:9000

  php:
    build: ./php
    volumes:
      - ./php/src:/var/www/html
    expose:
      - "9000"
    environment:
      SPOTIFY_CLIENT_ID: a184236c7732489eb9b4f3b549d6b65c
      SPOTIFY_CLIENT_SECRET: 3acc216d8d314569a95b75fb23be80f7
      TMDB_API_KEY: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxOGNiYjVkYTI1NzRmMWM0YmZlYWQ5MDZhNTY3ODJhYyIsIm5iZiI6MTczMDk4MzQzOS4zNzAxNTQ5LCJzdWIiOiI2NmYwMDY3ZjdmZjJiZjU3Y2QyNjRlN2MiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.POVQ9Y7M1-dwipH5Ijr1MiNx8a8xHqpnmwrCSwxht9w

  image-cache-batch:
    build:
      context: ./php
      dockerfile: ./Dockerfile
    volumes:
      - ./php/src:/var/www/html
    command:
      sh /var/www/html/saveImages.sh
    environment:
      SPOTIFY_CLIENT_ID: a184236c7732489eb9b4f3b549d6b65c
      SPOTIFY_CLIENT_SECRET: 3acc216d8d314569a95b75fb23be80f7
      TMDB_API_KEY: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxOGNiYjVkYTI1NzRmMWM0YmZlYWQ5MDZhNTY3ODJhYyIsIm5iZiI6MTczMDk4MzQzOS4zNzAxNTQ5LCJzdWIiOiI2NmYwMDY3ZjdmZjJiZjU3Y2QyNjRlN2MiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.POVQ9Y7M1-dwipH5Ijr1MiNx8a8xHqpnmwrCSwxht9w
    depends_on:
      - php

volumes:
  node_modules_test:
