services:
  react:
    build:
      args:
        - ENV_FILE=.env.production
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/fullchain_master.pem:/etc/nginx/certs/fullchain_master.pem:ro
      - /etc/ssl/private/letsencrypt33117937.key:/etc/nginx/certs/letsencrypt33117937.key:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_BASE_URL=https://rahi-lab.com/

  php:
    build: ./php
    volumes:
      - shared-data:/var/www/html
    expose:
      - "9000"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - TMDB_API_KEY=${TMDB_API_KEY}

  image-cache-batch:
    build:
      context: ./php
      dockerfile: ./Dockerfile
    user: "www-data"
    volumes:
      - shared-data:/var/www/html
    command:
      sh /var/www/html/saveImages.sh
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - TMDB_API_KEY=${TMDB_API_KEY}
    depends_on:
      - php

volumes:
  node_modules_override:
  shared-data: