services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env
        - NODE_VER=23-alpine3.20
    tty: true
    volumes:
      - ./frontend/nginx.test.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/ssl/private/letsencrypt33366955.key:/etc/nginx/certs/letsencrypt33366955.key:ro
      - /home/deploy_user/.htpasswd:/etc/nginx/htpasswd:ro
    ports:
      - "8081:80"
      - "8443:8443"
    depends_on:
      - php

  php:
    build: ./php
    expose:
      - "9000"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - TMDB_API_KEY=${TMDB_API_KEY}

  image-cache-batch:
    build:
      context: ./php
      dockerfile: ./Dockerfile
    command:
      sh /var/www/html/saveImages.sh
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
    depends_on:
      - php

volumes:
  node_modules_test:
