services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env
        - NODE_VER=23-alpine3.20
    tty: true
    ports:
      - "8081:80"
      - "8443:8443"
    depends_on:
      - php

  php:
    build: ./php
    expose:
      - "9000"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - TMDB_API_KEY=${TMDB_API_KEY}

  image-cache-batch:
    build:
      context: ./php
      dockerfile: ./Dockerfile
    command:
      sh /var/www/html/saveImages.sh
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
    depends_on:
      - php

volumes:
  node_modules_test:
