# services:
#   react:
#     build:
#       args:
#         - NODE_VER=23-alpine3.20
#       context: .
#       dockerfile: Dockerfile
#     tty: true
#     volumes:
#       - ./:/home/node/app

services:
  react:
    build:
      args:
        - NODE_VER=23-alpine3.20
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./frontend:/home/node/app/frontend
      - node_modules:/home/node/app/node_modules
    depends_on:
      - php
    environment:
      - VITE_API_BASE_URL=http://localhost

  php:
    build:
      args:
        SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
        SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
        TMDB_API_KEY: ${TMDB_API_KEY}
      context: ./php
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      TMDB_API_KEY: ${TMDB_API_KEY}

volumes:
  node_modules:
