services:
  react:
    build:
      args:
        - NODE_VER=20.17.0-slim
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./frontend:/home/node/app
      - node_modules:/home/node/app/node_modules
      - ./certs:/etc/nginx/certs # 証明書をマウント
    ports:
      - "80:80"
      - "443:443"

  php:
    build: ./php
    volumes:
      - ./php/src:/var/www/html
    expose:
      - "9000"

volumes:
  node_modules:
