services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env.test #テスト用の.env
        - NODE_VER=23-alpine3.20
    tty: true
    volumes:
      - ./frontend/nginx.test.conf:/etc/nginx/conf.d/default.conf
      - ./certs/dev:/etc/nginx/certs
    ports:
      - "8080:80"
      - "8443:8443"
    depends_on:
      - php
    environment:
      - VITE_API_BASE_URL=http://php:9000

volumes:
  node_modules_test:
