name: deploy_for_develop

on:
  push:
    branches:
      - dev
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: push_to_dev
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Add known_hosts
        run: |
          ssh-keyscan -H "${{ secrets.VPS_IP }}" >> ~/.ssh/known_hosts
        shell: bash

      - name: SSH and deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.DEPLOY_USER }}"@"${{ secrets.VPS_IP }}" << 'EOF'
            cd /var/www/test/best_react_ts/app
            sudo git fetch origin
            sudo git reset --hard origin/dev

            export SPOTIFY_CLIENT_ID="${{ secrets.SPOTIFY_CLIENT_ID }}"
            export SPOTIFY_CLIENT_SECRET="${{ secrets.SPOTIFY_CLIENT_SECRET }}"
            export TMDB_API_KEY="${{ secrets.TMDB_API_KEY }}"

            docker compose down
            docker compose -f docker-compose.yml -f docker-compose.dev.yml build --no-cache
          EOF