name: deploy_for_develop

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: push_to_dev
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Add known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts
        shell: bash
      - name: SSH and deploy to VPS
        run: |
          ssh ${{ secrets.github_actions }}@${{ secrets.VPS_IP }} << 'EOF'
            cd /var/www/test/dev_best
            git pull origin dev
            docker compose down
            docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
          EOF